version: '2'

services:
  # SSHD Server
  sshd:
    build: .
    environment:
      USERNAME: sftp
      PASSWORD: password
      # Should be the same as the volume mapping of app container
      FOLDER: /in
      # Optional: chroot
      CHROOT: 1
      # Optional: PORT
      PORT: 2238
    cap_add:
      # Required if you want to chroot
      - SYS_ADMIN
    security_opt:
      # Required if you want to chroot
      - apparmor:unconfined
    ports:
      - 2238:2238
