version: '2'

services:
  # SSHD Server
  sftp:
    build: .
    environment:
      USERNAME: sftp
      # Use custom mounted file as authorized_keys
      PUBLIC_KEYS_FILE: /etc/ssh/keys/ssh-key.pub
      # Should be the same as the volume mapping of app container
      FOLDER: /in
      # Optional: chroot
      CHROOT: 1
      # Optional: PORT
      PORT: 2238
    cap_add:
      # Required if you want to chroot
      - SYS_ADMIN
    security_opt:
      # Required if you want to chroot
      - apparmor:unconfined
    ports:
      - 2238:2238
    volumes:
      # Mount key files
      - ./spec/fixtures/files/keys/:/etc/ssh/keys:ro
      # Mount test files
      - ./spec/fixtures/files/sftp:/in

